name: Debug OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print Context
        run: |
          echo "Repository=$GITHUB_REPOSITORY"
          echo "Ref=$GITHUB_REF"
          echo "Actor=$GITHUB_ACTOR"
